import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import "./components/00_utilities/globals.scss";
import {Navigation} from "./components/03_organisms/Navigation/Navigation";
import {Footer} from "./components/03_organisms/Footer/Footer";
import localFont from "next/font/local";

const libreFranklin = localFont({
    variable: '--font-libre-franklin',
    src: '../public/fonts/LibreFranklin.ttf',
    subsets: ["latin"],
})

const inter = localFont({
    variable: '--font-inter',
    src: '../public/fonts/Inter.ttf',
    subsets: ["latin"],
})

//@todo replace metadata
export const metadata = {
  title: "Marion Dimbath",
  description: "Generated by create next app",
};
export default function RootLayout({children}){

  return (
      <html lang="en">
          <Head>
              <title>Marion Dimbath</title>
              <meta charSet="UTF-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
              <meta name="description" content="Your page description goes here"/>
              <link rel="canonical" href="https://yourwebsite.com/page-url"/>
          </Head>
        <body className={`${inter.variable} ${libreFranklin.variable} `}>
            <header>
                <Navigation/>
            </header>
            {children}
            <footer>
                <Footer/>
            </footer>
        </body>
      </html>
  )
}
